### ISSUE TITLE
VMD Pro

### ISSUE THREAD

**Issue by Earbuckets** [vuetifyjs/premium-theme-issues#3]
Doing some testing with light and dark theme switch and found that the sidebar filter colors do not change the primary colors only when using the light theme do the sidebar filter color selections work.

is there quick fix I cannot figure this for the life of me....

**Comment by Earbuckets** [comment]
Watching user storage initially the button doesn't swap the theme.  However, opening up the panel and toggling it back and forth it works but seems backwards.  Not sure if this helps

**Comment by ElijahKotyluk** [comment]
@Earbuckets, I just realized we are no longer the developers/maintainers of this theme, I would open up this issue here: https://www.creative-tim.com/contact-us
  - scroll down select: 'I have an issue with a product'
  - select the product (Vuetify Material Dashboard PRO)
  - click on the `Open a GitHub Issue`

They should be able to take care of this issue for you.
